# Here, load the packages you need for your workflow.

library(anomalize)
library(data.table)
library(drake)
library(fitdistrplus)
library(forecast)
library(ggplot2)
library(gridExtra)
library(lubridate)
library(magrittr)
library(MASS)
library(Metrics)
library(ompr)
library(ompr.roi)
library(plyr)
library(purrr)
library(queueing)
library(ROI)
library(ROI.plugin.glpk)
library(ROI.plugin.symphony)
library(tibbletime)
library(tidyr)
library(tidyverse)
library(zoo)
library(knitr)
library(rmarkdown)



pkgconfig::set_config("drake::strings_in_dots" = "literals")
